replicaCount: 1
image:
  repository: amitkkc01/akkcsupport
  tag: 6639cad07c2b7a8dc48694be46653fc9050f23df
  pullPolicy: Always
container:
  name: support-app
  port: 80
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
volume:
  name: support-html
  mountPath: /usr/share/nginx/html
configMap:
  suffix: configmap
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
