apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-app-svc

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Release.Name }}-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP