name: Deploy-multiple-charts_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger: none
pool:
  name: dev-aks-akkc-agent

variables:
  azureServiceConnection: 'Azure-SP'
  resourceGroup: 'aks-rg'
  aksCluster: 'aks-cluster'
  namespace: 'dev'

stages:

# ==========================
# Test Stage
- stage: Test
  displayName: Test Stage
  jobs:
  - job: Test
    displayName: Test Pipeline
    steps:
    - checkout: self
    - script: |
        echo "Deployment Starting..."
        ls -R $(Build.SourcesDirectory)
      displayName: Verify Repository


# Deploy Stage
# =========================
- stage: Deploy
  displayName: Deploy to AKS

  jobs:
  - job: HelmDeploy
    displayName: Helm Deployment
    steps:

    # Checkout Helm repo
    - checkout: git://akkc01/theakkcspace-deploy-aks-helm-argocd

    # Login to AKS
    - task: AzureCLI@2
      displayName: Login to AKS
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group $(resourceGroup) \
            --name $(aksCluster) \
            --overwrite-existing

    # Install Helm
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    # Deploy Main Chart
    - task: HelmDeploy@0
      displayName: Deploy Main Service
      inputs:
        connectionType: 'None'
        namespace: $(namespace)
        command: upgrade
        chartType: FilePath
        chartPath: theakkcspace-helm/main-chart
        releaseName: main-release
        install: true

    # Deploy Support Chart
    - task: HelmDeploy@0
      displayName: Deploy Support Service
      inputs:
        connectionType: 'None'
        namespace: $(namespace)
        command: upgrade
        chartType: FilePath
        chartPath: theakkcspace-helm/support-chart
        releaseName: support-release
        install: true

    # Deploy Email Chart
    - task: HelmDeploy@0
      displayName: Deploy Email Service
      inputs:
        connectionType: 'None'
        namespace: $(namespace)
        command: upgrade
        chartType: FilePath
        chartPath: theakkcspace-helm/email-chart
        releaseName: email-release
        install: true