apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}-app-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Email App</title>
      <style>
        body {
          font-family: Arial;
          text-align: center;
          margin-top: 100px;
          background-color: #f5f5f5;
        }
        h1 {
          color: blue;
          font-size: 50px;
        }
        p {
          font-size: 25px;
          color: green;
        }
      </style>
    </head>

    <body>
      <h1>Hello My Dear Friend</h1>
      <p>Welcome to Akkc's Email Services from AGIC Host-Based Ingress</p>
    </body>
    </html>
