replicaCount: 1
image:
  repository: amitkkc01/akkcmain
  tag: 03618da7d88e1664d1d3f3b4e4d0cb7b77e25a2c
  pullPolicy: Always
container:
  name: main-app-container
  port: 80
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
volume:
  name: main-html
  mountPath: /usr/share/nginx/html
configMap:
  suffix: configmap
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: theakkc.space # your domain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
