replicaCount: 1
image:
  repository: amitkkc01/akkcmain
  tag: 6d17b1550b663d6050b87a42c45e755b5334bb16
  pullPolicy: Always
container:
  name: main-app-container
  port: 80
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
volume:
  name: main-html
  mountPath: /usr/share/nginx/html
configMap:
  suffix: configmap
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: theakkc.space # your domain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
